### ISSUE TITLE
Cannot Bulid in Artix Linux

### ISSUE THREAD

**Issue by mobin-2008** [hexalang/hexa#18]
Hello, Im Try to Build hexa compiler for greentea os, i can not complate compile and see error:

/home/mobin/AUR/hexa/bootstrap.js:8331
			throw new CompilerErrors(this.hints);
			^
CompilerErrors {
  errors: [
    CompilerError {
      exception: 0,
      details: 'Expected `case` before `return`',
      line: 191,
      column: 9,
      fileName: '/home/mobin/AUR/hexa/source/compiler/normalizer.hexa'
    }
  ]
}
[mobin@Mobin-Mahdi-PC hexa]$ 

I think this problem is due to incorrect programming. Unfortunately I am not fluent in JavaScript. Thank you for helping me :)

My PC:
CPU= AMD Ryzen 5 3500X
GPU= NVIDIA Geforce GTX 1650
RAM= 2x8GB (16GB) CL16 - DDR4
OS= Artix Linux (Arch Linux + OpenRC init)

**Comment by PeyTy** [comment]
Try now

**Comment by PeyTy** [comment]
Linux builds now validated within CI
