### ISSUE TITLE
Syntax and Inspiration

### ISSUE THREAD

**Issue by PeyTy** [hexalang/hexa#4]
Hello [youse](http://mashable.com/2016/06/02/stop-saying-hey-guys/#2C7o.kps7kqq)! 😄 

This is the beginning of my [blog post series](https://github.com/hexalang/hexa/issues/3) about Hexa so let us start from basics!

First of all, Hexa was greatly inspired by [JavaScript](https://gist.github.com/royriojas/6454479). It consists of things people enjoy, want, find useful and [choose to be implemented](https://github.com/tc39/proposals).
Also, JavaScript has a most flexible yet sane syntax.

Other guys involved are: [TypeScript](http://www.typescriptlang.org), [Swift](http://www.apple.com/swift/) and, of course, [Haxe](http://haxe.org).

**TypeScript**'s popularity shows that dynamic typed scripting fades away. I love types. It solves a JavaScript+Types problem for me.

**Swift**'s team achieved high level of familiarity while rolled some pretty interesting, somewhat new, sometimes innovative, concepts and features. And yes, there is Apple's tyranny in language space on their platforms, which makes Swift [widely used](https://www.infoq.com/news/2016/01/swift-overtakes-objective-c) "by default". This is my second lowest common denominator for language look and feel.

**Haxe** is *more than 10 years old* language. Ahead of its time, years before it already looked like the todays mainstream. Haxe's main powers are astonishing type system, multiplatfrom support, meta-programming and [KISS principle](https://en.wikipedia.org/wiki/KISS_principle). It also follows JavaScript similarity.

You may expect a mix of features from those languages. Like [argument labels](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Functions.html) at a caller side, [nullability](https://blog.mariusschulz.com/2016/09/27/typescript-2-0-non-nullable-types) control, [tagged](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html) unions, object [extractors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), [standard](https://nodejs.org/api/fs.html) library, selective data [immutability](https://en.wikipedia.org/wiki/Immutable_object), etcetera.

As a mostly-systems programmer, I am surely under some influence of C++, Rust, Go, D, Nim, Red, Dafny, Haskell, Ada and maybe others too.

Stay tuned!

**Comment by mikicho** [comment]
Just a note: typescript and swift are not successful only because their magnificent architecture, you forget (or not forget...) to take in account 2 important parameters:
1. Those langs funds by the two of biggest corporations in the world
2. Programmers ego :) 
Also, I think you should add relevant hashtags on your tweets for more views. 
Michael

**Comment by PeyTy** [comment]
Hello, @mikicho!

1. This does not discard the desired effect. Take a look at top 20 of [TIOBE](http://www.tiobe.com/tiobe-index/). Top 4 languages are C, C-with-classes, C-with-garbage-collection and C-for-enterprise. Newest PHP7 also follows C++ and TypeScript style of syntax (with static types!). JavaScript is a scriptable C++ (well, actually, Java). Objective-C is... 😸 Others are not suitable for systems and strictly typed programming. I even do not consider Pascal and Basic because they are subject of hate for many programmers. WebAssembly is coming as a successor of JavaScript for web (sweet spot for Hexa). So it clearly looks for me that I may follow TypeScript, and it will be totally okay.
2. You mean: they actually *enjoy* those languages, despite of their architecture? :flushed: (Also, I do **not** think that either TS neither Swift are well architectured languages).
3. I'll widen audience after bootstrapping phase.

**Comment by PeyTy** [comment]
Moved to <https://hexalang.github.io/>
